version: '3.8'

services:
  sleep-help-app:
    build: .
    ports:
      - "3000:80"
    container_name: sleep-help-container
    restart: unless-stopped
    environment:
      - NODE_ENV=production
